name: Other
description: Describe anything here.
title: Other <subject>
labels: [question, Others]
assignees: MrKrishnaAgarwal
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else I should know about this issue?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also Follow me on [GitHub](https://github.com/MrKrishnaAgarwal), and [Twitter](https://twitter.com/DMKRISHNAA)
        Feel free to checkout my other cool [repositories](https://github.com/MrKrishnaAgarwal?tab=repositories) and [articles](https://dev.to/krishnaagarwal)
        <br>
        <img src= "https://octodex.github.com/images/supportcat.png" width="400">
        
