# Release to github using semantic versioning and conventional commits

name: GitHub Release
on:
  push:
    branches:
      - main

jobs:
  changelog:
    if: github.repository_owner == 'HackSquadDev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: create release
        uses: actions/create-release@main
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
